### ISSUE TITLE
Video is not uploaded to youtube account

### ISSUE THREAD

**Issue by manashegde** [Andreamoon/NodejsVideoUpLoad#1]
I followed the instruction and got the token and clientID. I launched the application later after choosing the video it prompted me to login to my account. The authentication did happen but video, not uploaded to youtube

**Comment by Andreamoon** [comment]
Hi @manashegde  you have to create a config folder on the root, and put credential.json with your credentials from youtube, in this format :
{
    "web": {
        "client_id": "*****",
        "project_id": "******",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "********",
        "redirect_uris": ["http://localhost:5000/auth/google/youtube"],
        "javascript_origins": ["http://localhost:5000"]
    }
}
